// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ3BjR2DQqnQjaRvMlJ7oEJag7RIb6bpc',
    appId: '1:897820166429:web:e8dd7e35be1727f24fb9f4',
    messagingSenderId: '897820166429',
    projectId: 'collabtasks-2bdf6',
    authDomain: 'collabtasks-2bdf6.firebaseapp.com',
    storageBucket: 'collabtasks-2bdf6.firebasestorage.app',
    measurementId: 'G-JK26S7HYFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCas1nx7Mu8F_YRsVYetFCWfslUe7icOr8',
    appId: '1:897820166429:android:349944b108e2b54c4fb9f4',
    messagingSenderId: '897820166429',
    projectId: 'collabtasks-2bdf6',
    storageBucket: 'collabtasks-2bdf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRhZJ7hx3A0cQNGoB-lxYBjmFNCXedlQ',
    appId: '1:897820166429:ios:4f1dfb9c4ab219e24fb9f4',
    messagingSenderId: '897820166429',
    projectId: 'collabtasks-2bdf6',
    storageBucket: 'collabtasks-2bdf6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnRhZJ7hx3A0cQNGoB-lxYBjmFNCXedlQ',
    appId: '1:897820166429:ios:4f1dfb9c4ab219e24fb9f4',
    messagingSenderId: '897820166429',
    projectId: 'collabtasks-2bdf6',
    storageBucket: 'collabtasks-2bdf6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ3BjR2DQqnQjaRvMlJ7oEJag7RIb6bpc',
    appId: '1:897820166429:web:cf1c29a413a345f84fb9f4',
    messagingSenderId: '897820166429',
    projectId: 'collabtasks-2bdf6',
    authDomain: 'collabtasks-2bdf6.firebaseapp.com',
    storageBucket: 'collabtasks-2bdf6.firebasestorage.app',
    measurementId: 'G-046B1ZRV1E',
  );

}